# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.4
  - nightly
notifications:
  email: false
jobs:
  allow_failures:
    - julia: nightly
  include:
    - stage: "Documentation"
      julia: 1
      os: linux
      script: |
        julia --project=docs -e '
          using Pkg
          Pkg.develop(PackageSpec(path=pwd()))
          Pkg.instantiate()
          include("docs/make.jl")'
      after_success: skip



