name = "StructuresKit"
uuid = "f6c18a9d-8941-4a0a-88a3-c5fc4dcc4715"
authors = ["Cris Moen"]
version = "0.1.0"

[compat]
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
