name = "StructuresKit"
uuid = "f6c18a9d-8941-4a0a-88a3-c5fc4dcc4715"
authors = ["Cris Moen"]
version = "0.1.0"

[deps]
DiffEqOperators = "9fdde737-9c7f-55bf-ade8-46b3f136cc48"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"

[compat]
julia = "1.4"
DiffEqOperators = "4"
NLsolve = "4"
RecursiveArrayTools = "2"


[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"

[targets]
test = ["Test", "SafeTestsets"]
